### ISSUE TITLE
Costs tab to-do

### ISSUE THREAD

**Issue by apmcguigan** [CS-4820-Library-Project/Libly#118]
- [ ] Vendor list does not update if new vendor is added or deleted. 
- [ ] Database dropdown, does not show full database name. (macOS)
- [ ] Check for any missing Original Currency options
- [ ] Re-label "Load from disk" to "Import Cost data"

If needed:
- [ ] Add Box to enter tax %
- [ ] Auto calculate final cost?
